# -*- extra stuff goes here -*-
from praesentationvonaufsatzinsammelband import IPraesentationvonAufsatzinSammelband
from rezensioneinerzeitschrift import IRezensioneinerZeitschrift
from praesentationenvonmonographien import IPraesentationenvonMonographien
from rezensioneinermonographie import IRezensioneinerMonographie
from rezension import IRezension
